#Inventory Connector Range
#Range: 4 ~ 256
inventoryConnectorRange = 32
#Only Allow Trims to Connect Inventories
onlyTrimsConnect = false
#Inventory Cable Connector Maximum number of cables
#Range: > 16
invCableConnectorMaxScanSize = 4848
#Wireless terminal reach
#Range: 4 ~ 64
wirelessReach = 64
#Wireless terminal reach
#Range: 16 ~ 512
advWirelessRange = 512
#Adv Wireless terminal requied beacon level for infinite range
#Value of 0 only requires a single beacon block nearby
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
wirelessTermBeaconLvl = 0
#Adv Wireless terminal requied beacon level for cross dimensional access
#Value of 0 only requires a single beacon block nearby
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
wirelessTermBeaconLvlDim = 0
#Inventory Cable Connector requied beacon level for inventory linking
#Value of 0 only requires a single beacon block
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
invLinkBeaconLvl = 0
#Inventory Cable Connector requied beacon level for cross dimensional access
#Value of 0 only requires a single beacon block
#Value of -1 disables this feature entirely
#Range: -1 ~ 4
invLinkBeaconLvlDim = 0
#Inventory Connector duplicate finder max slot count
#Value of 0 only disables
#Range: > 0
invDupScanSize = 100

